### ISSUE TITLE
Martinate does not use the -salt option

### ISSUE THREAD

**Issue by jbarnoud** [marrink-lab/gromit#20]
The `-salt` option of martinate is not pass on to insane. As a result, no ions are added regardless of the value given to `-salt`.

**Comment by OLaprevote** [comment]
In the version I currently have `martinate.sh --insane-salt=0.15` works perfectly fine. This issue can be marked as solved.

**Comment by Tsjerk** [comment]
Thank you for reporting this. I removed the option.
