### ISSUE TITLE
Options "-mdp" and "-dir" do not work together in martinate

### ISSUE THREAD

**Issue by jmelcr** [marrink-lab/gromit#24]
Options "-mdp" and "-dir" do not work together in martinate. It seems that the mdp file is expected to be in the simulation directory, but the path to it (from the argument of -mdp) is static and/or the mdp file is not copied to the new folder. 
An example code invoking this problem is:
`martinate.sh --insane-l=DPPC:168 --insane-sol=W --insane-d=10.0 --insane-dz=25 --insane-pbc=rectangular -dir sim01 -mdp my_mdp_file.mdp`

**Comment by Tsjerk** [comment]
I see that currently -dir will have more conflicts. Is the feature desirable, of is it better to remove it and leave setting up a new subdirectory to a user or enveloping script?
