### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by OLaprevote** [marrink-lab/gromit#26]
Given that the last issue and commits are 14 months or older here I feel reluctant to post any issue: is this repository still active? Should I post any issue there or should I go to [vermouth repository](https://github.com/marrink-lab/vermouth-martinize), or martini forum?

Same goes with pull requests: is it worth it that whenever I find and correct a bug/add a feature I do a pull request or is the code better left as is?

**Comment by Tsjerk** [comment]
The vermouth repo is a quite different project. Martinate and Gromit are auxiliary scripts for running martini and atomistic simulations, respectively. The programs are quite stable and are typically updated when needed (which happens more for martinate than for gromit). I'm quite open to (re)activate the development and to act on pull requests.
